### ISSUE TITLE
kaigionrailsのファイルに関するアクセス権について

### ISSUE THREAD

**Issue by okuramasafumi** [ruby-no-kai/dns#14]
`kaigionrails.org.lua`のファイルについて、Kaigi on Rails Teamの誰か、特に @unasuke がプッシュの権限を持っていると便利な場面が今後もあるかなと思います。可能でしたら権限をいただければと思います。

**Comment by unasuke** [comment]
得ました
https://github.com/ruby-no-kai/dns/pull/22#issuecomment-1493983514

**Comment by kakutani** [comment]
(かんぜんに失念しておりました…申し訳ないです)
