### ISSUE TITLE
rubykaigi.orgのサブドメインをSSL化したい

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/dns#9]
@amatsuda さんから話があって、cfp.rubykaigi.orgとsponsorship.rubykaigi.orgをSSL化したいとのことでした。

* SSLはCloudFlareを使いたい
* cfp.もsponsorship.も今年だけじゃなくて継続的に使えるようにしておきたい

**Comment by shyouhei** [comment]
- もともとは @kakutani さんがregionalのドメインをぽちぽちするための構成だった
- とはいえ @kakutani さんがSPOFになるのは困るので、もう少しワークフロー的に整理したいのでこうなった

**Comment by shyouhei** [comment]
NS自体を現在のluadnsからはがすには?

- SPOFが発生してしまう件を別途解決する必要がある

**Comment by takahashim** [comment]
こちらCloudFlareのアカウント作って対応したので閉じますね
